# Generated by Django 3.2.8 on 2021-11-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_feauterd',
            field=models.BooleanField(default=False),
        ),
    ]
